Ttree:
  Scheduler:
    allowParallelExecution: true
    lockStrategyClassName: 'Neos\Utility\Lock\FlockLockStrategy'
Neos:
  Flow:
    object:
      excludeClasses:
        beberlei.assert:
          - '.*'
        mtdowling.cronexpression:
          - '.*'
